import type { Item, Review } from '@aihub/shared';

export const items: Item[] = [
  {
    id: '1', name: 'ChatGPT', slug: 'chatgpt',
    description: 'OpenAI 旗舰 AI 对话工具，支持文本生成、分析和创意写作',
    longDescription: 'ChatGPT 是 OpenAI 开发的先进 AI 对话助手，基于 GPT 系列模型。它能够进行自然对话、回答问题、撰写文章、编写代码、翻译语言等多种任务。',
    url: 'https://chat.openai.com', affiliateUrl: 'https://chat.openai.com',
    logo: '',
    category: '聊天机器人', categorySlug: 'chatbot',
    pricingModel: 'freemium', pricingDetail: '免费版可用 GPT-3.5，Plus $20/月，Pro $200/月',
    featured: true, rating: 4.8, reviewCount: 256, upvotes: 1892,
    features: ['多模态交互', '联网搜索', '文件上传分析', 'DALL-E 图像生成', '语音对话'],
    pros: ['功能全面', '响应速度快', '持续更新', '免费版够用'],
    cons: ['中文理解偶有偏差', 'Pro 版价格较高', '高峰期可能排队'],
    screenshots: [],
    createdAt: '2024-01-01'
  },
  {
    id: '2', name: 'Claude', slug: 'claude',
    description: 'Anthropic 安全智能 AI 助手，擅长长文分析和代码',
    longDescription: 'Claude 是 Anthropic 开发的 AI 助手系列，以安全性和长文本处理能力著称。Claude 3.5 Sonnet 在编程和推理任务上表现突出，支持 200K token 的超长上下文。',
    url: 'https://claude.ai', affiliateUrl: 'https://claude.ai',
    logo: '',
    category: '聊天机器人', categorySlug: 'chatbot',
    pricingModel: 'freemium', pricingDetail: '免费版可用，Pro $20/月，Team $25/人/月',
    featured: true, rating: 4.7, reviewCount: 189, upvotes: 1543,
    features: ['超长上下文', '代码质量高', '安全对齐', 'Artifacts 功能', '项目协作'],
    pros: ['长文本无敌', '代码能力强', '安全性好', '中文流畅'],
    cons: ['文件上传限制', '无图像生成', '更新频率较低'],
    screenshots: [],
    createdAt: '2024-01-15'
  },
  {
    id: '3', name: 'GitHub Copilot', slug: 'github-copilot',
    description: 'AI 编程助手，实时代码补全和生成',
    longDescription: 'GitHub Copilot 是 GitHub 和 OpenAI 联合推出的 AI 编程助手，集成在 VS Code、JetBrains 等主流 IDE 中。支持代码补全、函数生成、测试编写、代码解释等功能。',
    url: 'https://github.com/features/copilot', affiliateUrl: 'https://github.com/features/copilot',
    logo: '',
    category: '编程助手', categorySlug: 'coding',
    pricingModel: 'paid', pricingDetail: '个人 $10/月，企业 $19/用户/月',
    featured: true, rating: 4.6, reviewCount: 312, upvotes: 2103,
    features: ['实时代码补全', '多语言支持', 'IDE 集成', '代码解释', 'Chat 模式'],
    pros: ['大幅提升编码效率', '支持语言多', '与 IDE 深度集成'],
    cons: ['依赖网络', '有时生成不安全代码', '个人版偏贵'],
    screenshots: [],
    createdAt: '2024-02-01'
  },
  {
    id: '4', name: 'Midjourney', slug: 'midjourney',
    description: '顶级 AI 图像生成工具，艺术风格出众',
    longDescription: 'Midjourney 是目前最受欢迎的 AI 图像生成工具之一，以其独特的艺术风格和高品质输出著称。通过 Discord 使用，支持文生图和图生图。',
    url: 'https://www.midjourney.com', affiliateUrl: '',
    logo: '',
    category: '图像生成', categorySlug: 'image-generation',
    pricingModel: 'paid', pricingDetail: '基础 $10/月，标准 $30/月，专业 $60/月',
    featured: true, rating: 4.7, reviewCount: 178, upvotes: 1678,
    features: ['文生图', '图生图', '风格一致', '放大和变体', '参数控制'],
    pros: ['图像质量极高', '艺术感强', '风格多样', '社区活跃'],
    cons: ['需通过 Discord 使用', '价格较高', '中文提示词效果一般'],
    screenshots: [],
    createdAt: '2024-01-10'
  },
  {
    id: '5', name: 'Suno', slug: 'suno',
    description: 'AI 音乐生成工具，文字转完整歌曲',
    longDescription: 'Suno 是领先的 AI 音乐生成平台，只需输入歌词和风格描述即可生成完整的歌曲，包括人声、乐器、混音。支持多种音乐流派和语言。',
    url: 'https://suno.com', affiliateUrl: 'https://suno.com',
    logo: '',
    category: '音频工具', categorySlug: 'audio',
    pricingModel: 'freemium', pricingDetail: '免费每天 5 首，Pro $10/月（500首），Premier $30/月（2000首）',
    featured: true, rating: 4.5, reviewCount: 98, upvotes: 876,
    features: ['文字转音乐', '多种音乐风格', '多语言支持', '歌词编辑', '音频延长'],
    pros: ['创作门槛极低', '音乐质量惊艳', '风格丰富'],
    cons: ['免费额度少', '中文歌词发音偶有问题', '版权归属需注意'],
    screenshots: [],
    createdAt: '2024-03-01'
  },
  {
    id: '6', name: 'Cursor', slug: 'cursor',
    description: 'AI-first 代码编辑器，内置智能编程功能',
    longDescription: 'Cursor 是基于 VS Code 的 AI 原生代码编辑器，深度集成 AI 编程能力。支持 Tab 补全、多文件编辑、AI Chat、代码库理解等功能。',
    url: 'https://cursor.sh', affiliateUrl: 'https://cursor.sh',
    logo: '',
    category: '编程助手', categorySlug: 'coding',
    pricingModel: 'freemium', pricingDetail: '免费版可用，Pro $20/月',
    featured: false, rating: 4.6, reviewCount: 234, upvotes: 1890,
    features: ['AI 补全', '多文件编辑', '代码库索引', 'Agent 模式', '终端集成'],
    pros: ['编程效率提升显著', '代码理解准确', '免费版够用'],
    cons: ['基于 VS Code 有延迟', '大项目索引慢', '企业版定价偏高'],
    screenshots: [],
    createdAt: '2024-04-01'
  },
  {
    id: '7', name: 'Gemini', slug: 'gemini',
    description: 'Google 多模态 AI 助手，深度集成 Google 生态',
    longDescription: 'Gemini 是 Google 开发的 AI 助手系列，支持文本、图像、音频、视频等多模态输入。',
    url: 'https://gemini.google.com', affiliateUrl: '',
    logo: '',
    category: '聊天机器人', categorySlug: 'chatbot',
    pricingModel: 'freemium', pricingDetail: '免费版可用，Advanced $19.99/月',
    featured: false, rating: 4.4, reviewCount: 145, upvotes: 1102,
    features: ['多模态输入', 'Google 生态集成', '长上下文', '实时信息', '文件分析'],
    pros: ['免费版功能强', '与 Google 服务无缝集成', '多模态能力好'],
    cons: ['中文优化一般', '隐私担忧', '部分功能地区限制'],
    screenshots: [],
    createdAt: '2024-02-15'
  },
  {
    id: '8', name: 'Perplexity', slug: 'perplexity',
    description: 'AI 搜索引擎，带引用来源的实时答案',
    longDescription: 'Perplexity 是 AI 驱动的搜索引擎，提供带引用来源的实时答案。',
    url: 'https://www.perplexity.ai', affiliateUrl: '',
    logo: '',
    category: 'AI 搜索', categorySlug: 'ai-search',
    pricingModel: 'freemium', pricingDetail: '免费版可用，Pro $20/月',
    featured: false, rating: 4.5, reviewCount: 167, upvotes: 1345,
    features: ['实时搜索', '引用来源', '研究模式', '文件上传分析', '合集整理'],
    pros: ['答案准确可溯源', '研究效率高', '免费版好用'],
    cons: ['深度不如 ChatGPT', '国内访问受限', 'Pro 版优势不明显'],
    screenshots: [],
    createdAt: '2024-01-20'
  },
  {
    id: '9', name: 'Runway', slug: 'runway',
    description: 'AI 视频生成和编辑平台，Gen-3 模型领先',
    longDescription: 'Runway 是领先的 AI 视频生成平台，其 Gen-3 Alpha 模型能生成高质量视频内容。',
    url: 'https://runwayml.com', affiliateUrl: '',
    logo: '',
    category: '视频生成', categorySlug: 'video-generation',
    pricingModel: 'paid', pricingDetail: '基础 $12/月，标准 $28/月，专业 $76/月',
    featured: false, rating: 4.3, reviewCount: 87, upvotes: 765,
    features: ['文生视频', '图生视频', '视频编辑', '运动笔刷', '绿幕去除'],
    pros: ['视频质量行业领先', '专业工具集', '持续更新快'],
    cons: ['价格较高', '中文理解弱', '生成速度有待提升'],
    screenshots: [],
    createdAt: '2024-03-15'
  },
  {
    id: '10', name: 'Notion AI', slug: 'notion-ai',
    description: '集成 AI 的笔记和项目管理平台',
    longDescription: 'Notion AI 将 AI 能力集成到 Notion 的笔记、文档和项目管理中。',
    url: 'https://www.notion.so/product/ai', affiliateUrl: '',
    logo: '',
    category: '办公效率', categorySlug: 'productivity',
    pricingModel: 'paid', pricingDetail: 'AI 附加 $10/人/月',
    featured: false, rating: 4.4, reviewCount: 123, upvotes: 987,
    features: ['AI 写作', '自动摘要', '翻译', '头脑风暴', '数据库 AI'],
    pros: ['与 Notion 深度集成', '写作辅助强', '团队协作好'],
    cons: ['需已有 Notion 订阅', 'AI 功能偏基础', '国内访问慢'],
    screenshots: [],
    createdAt: '2024-02-20'
  },
  {
    id: '11', name: 'Devin', slug: 'devin',
    description: '全自主 AI 软件工程师，能独立完成编程任务',
    longDescription: 'Devin 是 Cognition Labs 推出的全自主 AI 软件工程师。它能理解复杂任务、编写代码、调试、部署。',
    url: 'https://cognition.ai', affiliateUrl: '',
    logo: '',
    category: '编程助手', categorySlug: 'coding',
    pricingModel: 'paid', pricingDetail: '起价 $500/月（企业定制定价）',
    featured: false, rating: 4.2, reviewCount: 56, upvotes: 654,
    features: ['自主编程', '调试修复', '部署上线', '技术学习', '项目管理'],
    pros: ['能独立完成项目', '减少人工编码', '持续学习'],
    cons: ['价格极高', '复杂项目仍需人工', '学习曲线陡'],
    screenshots: [],
    createdAt: '2024-05-01'
  },
];

export const reviews: Review[] = [
  {
    id: '1', itemId: '1',
    author: 'AI 爱好者', rating: 5,
    title: '日常必备的 AI 工具',
    content: 'ChatGPT 已经成了我每天工作离不开的工具。写邮件、做总结、头脑风暴，甚至写代码都能帮上忙。',
    pros: '功能全面，免费版够用',
    cons: '偶尔高峰期会卡顿',
    createdAt: '2025-06-01'
  },
  {
    id: '2', itemId: '1',
    author: '程序员小王', rating: 4,
    title: '中文能力有提升空间',
    content: '整体体验很好，但中文理解有时会出现偏差，尤其是专业术语和成语。',
    pros: '英文能力极强，知识面广',
    cons: '中文理解需要改进',
    createdAt: '2025-05-15'
  },
  {
    id: '3', itemId: '3',
    author: '全栈开发者', rating: 5,
    title: '写代码效率翻倍',
    content: '用了 Copilot 之后，编码速度至少提升了 50%。',
    pros: '补全准确率高，支持语言多',
    cons: '价格略贵',
    createdAt: '2025-04-20'
  },
];